### ISSUE TITLE
Adapter Is Not working

### ISSUE THREAD

**Issue by gorfadvijay** [jz222/loggy-adapter-nodejs#1]
how to join adapter with https://loggy-demo.web.app/

here is my code 

`
loggy.init({
    instance: 'Jarviot',
    endpoint: 'https://loggy-demo.web.app/',
    ticket: 'F3CE542A5D9F339C4A4C3F012B4E27E08274DE35636DA4B4DE'
});
`

**Comment by jz222** [comment]
You are using the demo instance of LOGGY. This means you need to set the `instance` key in your config to `demo`. The `endpoint` property is only necessary if you are hosting LOGGY yourself.

```javascript
loggy.init({ instance: 'demo', ticket: 'F3CE542A5D9F339C4A4C3F012B4E27E08274DE35636DA4B4DE' });
```

Please notice that everyone who knows the ticket is able to attach logs to your service.
